FROM fusuf/whatsasena:latest

RUN git clone https://github.com/Afx-Abu/Alexa /jsl/Alexa
WORKDIR /jsl/Alexa/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
RUN yarn install --ignore-engines
RUN git clone https://github.com/Afx-Abu/bgms

CMD ["node", "bot.js"]
